### ISSUE TITLE
4.4.x Release Todo

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#82]
Overview of thing to be done in the next mayor 4.4.x release
- [x] Tooltips (missing stack switcher)
- [ ] Cleanup/Redesign Group page 
- [ ] Cleanup/Redesign the History Page
- [x] Ctrl - F for open search bar ( allready bound to quick search in package view)
- [x] Make **Apply Pending** insensitive when there is nothing in queue
- [x] Fix: flickering when changing package info buttons.
- [x] Use popover menu for main menu also
- [x] store search option between session
- [x] add rightclick menu to queue view
- [x] no reload of dnf metadata, when refresh_interval = 0

**Comment by genodeftest** [comment]
Another thing missing before 4.4 release is pulling in translation updates from transifex.
